tls.enabled=true
tls.cert.path=/app/tls/server.crt
tls.private.key.path=/app/tls/server.key

http.bind.to=0.0.0.0:9000
http.min.bind.to=0.0.0.0:9003
pg.net.bind.to=0.0.0.0:8812
line.tcp.net.bind.to=0.0.0.0:9009

cairo.wal.enabled.default=true
